@httpApiKey = sk_example_http_key

### GET status
GET http://192.168.10.124/status
Authorization: Bearer {{httpApiKey}}

### GET sensor reading
GET http://192.168.10.124/read
Authorization: Bearer {{httpApiKey}}

### GET metrics
GET http://192.168.10.124/metrics
Authorization: Bearer {{httpApiKey}}

### GET config
GET http://192.168.10.124/config
Authorization: Bearer {{httpApiKey}}

### POST config
POST http://192.168.10.124/config
Content-Type: application/json
Authorization: Bearer {{httpApiKey}}

{
      "api_key": "sk_example_key",
      "http_api_key": "sk_example_http_key"
}

### save config
POST http://192.168.10.124/config/save
Authorization: Bearer {{httpApiKey}}

### discard config
POST http://192.168.10.124/config/discard
Authorization: Bearer {{httpApiKey}}

### reset
POST http://192.168.10.124/config/factory_reset
Authorization: Bearer {{httpApiKey}}